# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/remco/Final_Project_AES/Final_Project_AES.srcs/sources_1/bd/Block_Diagram/ip/Block_Diagram_axi_gpio_2_0/Block_Diagram_axi_gpio_2_0.xci
# IP: The module: 'Block_Diagram_axi_gpio_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/remco/Final_Project_AES/Final_Project_AES.srcs/sources_1/bd/Block_Diagram/ip/Block_Diagram_axi_gpio_2_0/Block_Diagram_axi_gpio_2_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Block_Diagram_axi_gpio_2_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/remco/Final_Project_AES/Final_Project_AES.srcs/sources_1/bd/Block_Diagram/ip/Block_Diagram_axi_gpio_2_0/Block_Diagram_axi_gpio_2_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Block_Diagram_axi_gpio_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/remco/Final_Project_AES/Final_Project_AES.srcs/sources_1/bd/Block_Diagram/ip/Block_Diagram_axi_gpio_2_0/Block_Diagram_axi_gpio_2_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Block_Diagram_axi_gpio_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/remco/Final_Project_AES/Final_Project_AES.srcs/sources_1/bd/Block_Diagram/ip/Block_Diagram_axi_gpio_2_0/Block_Diagram_axi_gpio_2_0.xci
# IP: The module: 'Block_Diagram_axi_gpio_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/remco/Final_Project_AES/Final_Project_AES.srcs/sources_1/bd/Block_Diagram/ip/Block_Diagram_axi_gpio_2_0/Block_Diagram_axi_gpio_2_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Block_Diagram_axi_gpio_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/remco/Final_Project_AES/Final_Project_AES.srcs/sources_1/bd/Block_Diagram/ip/Block_Diagram_axi_gpio_2_0/Block_Diagram_axi_gpio_2_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Block_Diagram_axi_gpio_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/remco/Final_Project_AES/Final_Project_AES.srcs/sources_1/bd/Block_Diagram/ip/Block_Diagram_axi_gpio_2_0/Block_Diagram_axi_gpio_2_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Block_Diagram_axi_gpio_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
