# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Desktop/Zybo-Z7-Master.xdc

# Block Designs: bd/Block_Diagram/Block_Diagram.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Block_Diagram || ORIG_REF_NAME==Block_Diagram} -quiet] -quiet

# IP: bd/Block_Diagram/ip/Block_Diagram_processing_system7_0_0/Block_Diagram_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Block_Diagram_processing_system7_0_0 || ORIG_REF_NAME==Block_Diagram_processing_system7_0_0} -quiet] -quiet

# IP: bd/Block_Diagram/ip/Block_Diagram_quadrature_decoder_0_0/Block_Diagram_quadrature_decoder_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Block_Diagram_quadrature_decoder_0_0 || ORIG_REF_NAME==Block_Diagram_quadrature_decoder_0_0} -quiet] -quiet

# IP: bd/Block_Diagram/ip/Block_Diagram_xlconstant_0_0/Block_Diagram_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Block_Diagram_xlconstant_0_0 || ORIG_REF_NAME==Block_Diagram_xlconstant_0_0} -quiet] -quiet

# IP: bd/Block_Diagram/ip/Block_Diagram_pwm_0_0/Block_Diagram_pwm_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Block_Diagram_pwm_0_0 || ORIG_REF_NAME==Block_Diagram_pwm_0_0} -quiet] -quiet

# IP: bd/Block_Diagram/ip/Block_Diagram_axi_gpio_0_0/Block_Diagram_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Block_Diagram_axi_gpio_0_0 || ORIG_REF_NAME==Block_Diagram_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Block_Diagram/ip/Block_Diagram_ps7_0_axi_periph_0/Block_Diagram_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Block_Diagram_ps7_0_axi_periph_0 || ORIG_REF_NAME==Block_Diagram_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Block_Diagram/ip/Block_Diagram_rst_ps7_0_50M_0/Block_Diagram_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Block_Diagram_rst_ps7_0_50M_0 || ORIG_REF_NAME==Block_Diagram_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/Block_Diagram/ip/Block_Diagram_PID_0_1/Block_Diagram_PID_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Block_Diagram_PID_0_1 || ORIG_REF_NAME==Block_Diagram_PID_0_1} -quiet] -quiet

# IP: bd/Block_Diagram/ip/Block_Diagram_axi_gpio_1_0/Block_Diagram_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Block_Diagram_axi_gpio_1_0 || ORIG_REF_NAME==Block_Diagram_axi_gpio_1_0} -quiet] -quiet

# IP: bd/Block_Diagram/ip/Block_Diagram_xbar_0/Block_Diagram_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Block_Diagram_xbar_0 || ORIG_REF_NAME==Block_Diagram_xbar_0} -quiet] -quiet

# IP: bd/Block_Diagram/ip/Block_Diagram_invert_top_0_0/Block_Diagram_invert_top_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Block_Diagram_invert_top_0_0 || ORIG_REF_NAME==Block_Diagram_invert_top_0_0} -quiet] -quiet

# IP: bd/Block_Diagram/ip/Block_Diagram_axi_gpio_2_0/Block_Diagram_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Block_Diagram_axi_gpio_2_0 || ORIG_REF_NAME==Block_Diagram_axi_gpio_2_0} -quiet] -quiet

# IP: bd/Block_Diagram/ip/Block_Diagram_axi_gpio_3_0/Block_Diagram_axi_gpio_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Block_Diagram_axi_gpio_3_0 || ORIG_REF_NAME==Block_Diagram_axi_gpio_3_0} -quiet] -quiet

# IP: bd/Block_Diagram/ip/Block_Diagram_axi_gpio_4_0/Block_Diagram_axi_gpio_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Block_Diagram_axi_gpio_4_0 || ORIG_REF_NAME==Block_Diagram_axi_gpio_4_0} -quiet] -quiet

# IP: bd/Block_Diagram/ip/Block_Diagram_axi_gpio_5_0/Block_Diagram_axi_gpio_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Block_Diagram_axi_gpio_5_0 || ORIG_REF_NAME==Block_Diagram_axi_gpio_5_0} -quiet] -quiet

# IP: bd/Block_Diagram/ip/Block_Diagram_clk_div_0_0/Block_Diagram_clk_div_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Block_Diagram_clk_div_0_0 || ORIG_REF_NAME==Block_Diagram_clk_div_0_0} -quiet] -quiet

# IP: bd/Block_Diagram/ip/Block_Diagram_xlconstant_1_0/Block_Diagram_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Block_Diagram_xlconstant_1_0 || ORIG_REF_NAME==Block_Diagram_xlconstant_1_0} -quiet] -quiet

# IP: bd/Block_Diagram/ip/Block_Diagram_axi_gpio_6_0/Block_Diagram_axi_gpio_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Block_Diagram_axi_gpio_6_0 || ORIG_REF_NAME==Block_Diagram_axi_gpio_6_0} -quiet] -quiet

# IP: bd/Block_Diagram/ip/Block_Diagram_auto_pc_0/Block_Diagram_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Block_Diagram_auto_pc_0 || ORIG_REF_NAME==Block_Diagram_auto_pc_0} -quiet] -quiet

# XDC: bd/Block_Diagram/Block_Diagram_ooc.xdc
