#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2018.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Jan 06 14:51:38 CET 2020
# SW Build 2258646 on Thu Jun 14 20:02:38 MDT 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
ExecStep xelab -wto 8a0d197d9042446eaae90fb761ac503d --incr --debug typical --relax --mt 8 --include "../../../../Final_Project_AES.srcs/sources_1/bd/Block_Diagram/ip/Block_Diagram_xlconstant_0_0/sysc" --include "../../../../Final_Project_AES.srcs/sources_1/bd/Block_Diagram/ip/Block_Diagram_xlconstant_0_0/sim" --include "../../../../Final_Project_AES.srcs/sources_1/bd/Block_Diagram/ip/Block_Diagram_xlconstant_1_2/sysc" --include "../../../../Final_Project_AES.srcs/sources_1/bd/Block_Diagram/ip/Block_Diagram_xlconstant_1_2/sim" -L xil_defaultlib -L axi_infrastructure_v1_1_0 -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_3 -L axi_vip_v1_1_3 -L processing_system7_vip_v1_0_5 -L xlconstant_v1_1_5 -L axi_lite_ipif_v3_0_4 -L lib_cdc_v1_0_2 -L interrupt_control_v3_1_4 -L axi_gpio_v2_0_19 -L proc_sys_reset_v5_0_12 -L generic_baseblocks_v2_1_0 -L axi_register_slice_v2_1_17 -L fifo_generator_v13_2_2 -L axi_data_fifo_v2_1_16 -L axi_crossbar_v2_1_18 -L axi_protocol_converter_v2_1_17 -L xilinx_vip -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot Block_Diagram_wrapper_behav xil_defaultlib.Block_Diagram_wrapper xil_defaultlib.glbl -log elaborate.log
