#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2018.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Jan 06 14:52:07 CET 2020
# SW Build 2258646 on Thu Jun 14 20:02:38 MDT 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
ExecStep xsim Block_Diagram_wrapper_behav -key {Behavioral:sim_1:Functional:Block_Diagram_wrapper} -tclbatch Block_Diagram_wrapper.tcl -view /home/remco/Final_Project_AES/Block_Diagram_wrapper_behav.wcfg -log simulate.log
