set_property SRC_FILE_INFO {cfile:/home/remco/Final_Project_AES/Final_Project_AES.srcs/constrs_1/imports/Desktop/Zybo-Z7-Master.xdc rfile:../../../Final_Project_AES.srcs/constrs_1/imports/Desktop/Zybo-Z7-Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN V12   IOSTANDARD LVCMOS33 } [get_ports { A }]; #IO_L4P_T0_34 Sch=je[1]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN W16   IOSTANDARD LVCMOS33 } [get_ports { B }]; #IO_L18N_T2_34 Sch=je[2]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN J15   IOSTANDARD LVCMOS33 } [get_ports { pwm[0] }]; #IO_25_35 Sch=je[3]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN H15   IOSTANDARD LVCMOS33 } [get_ports { Direction[0] }]; #IO_L19P_T3_35 Sch=je[4]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN V13   IOSTANDARD LVCMOS33 } [get_ports { InvDirection[0] }]; #IO_L3N_T0_DQS_34 Sch=je[7]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN K18   IOSTANDARD LVCMOS33 } [get_ports { restart }]; #IO_L12N_T1_MRCC_35 Sch=btn[0]
